export const ADD_TO_CART ="ADD_TO_CART";
export const CHANGE_MESSAGE ="CHANGE_MESSAGE";

export const DELETE_PRODUCT_INCART ="DELETE_PRODUCT_INCART";
export const UPDATE_PRODUCT_IN_CART ="UPDATE_PRODUCT_IN_CART";